spring.application.name=database

# Conexão JDBC
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Chave JWT
api.security.token.secret=${JWT_SECRET}

app.cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs